#!/usr/bin/env bash
#
# Configure newsyslog rotation for the two llama-swap logs.
#
#   scripts/log-rotation.sh --dry-run    # print the config, touch nothing
#   scripts/log-rotation.sh --check      # exit 0 if already correct
#   sudo scripts/log-rotation.sh         # write /etc/newsyslog.d/llama-swap.conf
#
# Without this the logs grow unbounded — llama-swap.log is mostly editors
# polling /models/sse at 404, which adds up fast.
#
# The owner:group column is mandatory for user-owned files. Omit it and
# newsyslog creates the rotated files root-owned, after which llama-swap can no
# longer write its own log — a worse failure than no rotation at all. So the
# owner is resolved from the invoking account rather than hardcoded, and
# resolved correctly under sudo, where `id -un` would say root.

set -euo pipefail

CONF="${LOCALAI_NEWSYSLOG_CONF:-/etc/newsyslog.d/llama-swap.conf}"

die() { printf 'error: %s\n' "$1" >&2; exit 2; }

# Under sudo, SUDO_USER is the account that invoked it. Falling back to `id -un`
# covers a root shell, where there is nothing better to go on.
resolve_user() {
    local u="${LOCALAI_LOG_USER:-${SUDO_USER:-$(id -un)}}"
    if [ "$u" = "root" ]; then
        die "cannot tell whose logs to rotate — run via sudo from your own account"
    fi
    printf '%s' "$u"
}

# dscl is the source of truth on macOS; ~expansion is the fallback for anywhere
# a home directory is not where the account database says it is.
resolve_home() {
    local u="$1" h=""
    if [ -n "${LOCALAI_LOG_HOME:-}" ]; then
        printf '%s' "$LOCALAI_LOG_HOME"; return 0
    fi
    h="$(dscl . -read "/Users/$u" NFSHomeDirectory 2>/dev/null | awk '{print $2}')" || true
    if [ -z "$h" ]; then
        h="$(eval printf '%s' "~$u")"
    fi
    [ -n "$h" ] || die "could not resolve a home directory for $u"
    # ~expansion leaves "~alex" untouched for an account that does not exist,
    # which would otherwise be written into the config as a literal path.
    case "$h" in
        /*) ;;
        *)  die "resolved a non-absolute home for $u: $h" ;;
    esac
    printf '%s' "$h"
}

# newsyslog.conf columns: path owner:group mode count size when flags
#   644    mode of the rotated file
#   5      keep five generations
#   10240  rotate at 10MB (the size column is in KB)
#   *      no time-based rotation, size only
#   BN     B: no "logfile turned over" line injected into the log
#          N: there is no process to signal — llama-swap holds the fd via
#             launchd, so writes only move to the fresh file after the next
#             service restart. Fine on a laptop.
render() {
    local user="$1" group="$2" home="$3" out err width
    out="$home/Library/Logs/llama-swap.log"
    err="$home/Library/Logs/llama-swap.error.log"
    width=${#err}

    printf '# generated by local-ai-setup — scripts/log-rotation.sh\n'
    printf '# regenerate rather than hand-edit; owner:group must match the log owner\n'
    printf '%-*s  %s:%s  644  5  10240  *  BN\n' "$width" "$out" "$user" "$group"
    printf '%-*s  %s:%s  644  5  10240  *  BN\n' "$width" "$err" "$user" "$group"
}

MODE="apply"
case "${1:-}" in
    --dry-run) MODE="dry-run" ;;
    --check)   MODE="check" ;;
    -h|--help) sed -n '3,9p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    "")        ;;
    *)         die "unknown option: $1" ;;
esac

USER_NAME="$(resolve_user)"
GROUP_NAME="$(id -gn "$USER_NAME" 2>/dev/null || printf 'staff')"
HOME_DIR="$(resolve_home "$USER_NAME")"

TMP="$(mktemp "${TMPDIR:-/tmp}/llama-swap-newsyslog.XXXXXX")"
trap 'rm -f "$TMP"' EXIT
render "$USER_NAME" "$GROUP_NAME" "$HOME_DIR" >"$TMP"

case "$MODE" in
check)
    if [ -f "$CONF" ] && diff -q "$TMP" "$CONF" >/dev/null 2>&1; then
        printf '%s (%s:%s)\n' "$CONF" "$USER_NAME" "$GROUP_NAME"
        exit 0
    fi
    if [ -f "$CONF" ]; then
        printf '%s exists but does not match this machine\n' "$CONF"
    else
        printf 'not configured — %s is absent\n' "$CONF"
    fi
    exit 1
    ;;
dry-run)
    printf 'user   %s:%s\n' "$USER_NAME" "$GROUP_NAME"
    printf 'home   %s\n' "$HOME_DIR"
    printf 'target %s\n\n' "$CONF"
    cat "$TMP"
    ;;
apply)
    if [ -f "$CONF" ] && diff -q "$TMP" "$CONF" >/dev/null 2>&1; then
        printf 'already correct — nothing to do\n'
        exit 0
    fi
    if [ ! -w "$(dirname "$CONF")" ]; then
        die "cannot write $(dirname "$CONF") — run: sudo $0"
    fi

    # Parse it before installing it. A malformed fragment makes newsyslog skip
    # the whole file, which fails silently and looks exactly like working.
    # `newsyslog -n` insists on root even to parse, so this only runs on the
    # sudo path — which is the one that writes to /etc, so that is where it counts.
    if [ "$(id -u)" -eq 0 ] && command -v newsyslog >/dev/null 2>&1; then
        newsyslog -n -f "$TMP" >/dev/null 2>&1 ||
            die "newsyslog rejected the generated config — see: newsyslog -nv -f $TMP"
    fi

    install -m 0644 "$TMP" "$CONF"
    printf 'wrote %s\n' "$CONF"
    printf 'owner %s:%s\n' "$USER_NAME" "$GROUP_NAME"
    ;;
esac
