# steps/40-configs.sh — generate the llama-swap config and Pi's model list.
#
# models.yaml is the only input. Both outputs are rendered to a temp file and
# installed only when they differ from what is live, so a no-op run is silent
# and the service is never restarted for nothing.
#
# Sourced by setup.sh.
# shellcheck shell=bash

section "configs"

# See the note in 30-models.sh: on a fresh machine these arrive with the tools
# step, so a full --dry-run legitimately runs without them and must still exit 0.
_cfg_missing=""
have yq || _cfg_missing="yq"
have jq || _cfg_missing="${_cfg_missing:+$_cfg_missing and }jq"
if [ -n "$_cfg_missing" ]; then
    if is_dry; then
        skip "configs ($_cfg_missing not installed yet — the tools step installs that)"
    else
        fail "$_cfg_missing is required to generate the configs — run the tools step first"
    fi
    return 0
fi

GEN_HEADER="# GENERATED by local-ai-setup — edit models.yaml instead"

# ── manifest validation ──────────────────────────────────────────────────────
# Two classes of manifest value are legal YAML but wrong here, and both fail
# silently rather than loudly. Catching them at the source names the offending
# field; the parse gate in install_generated() is the backstop that catches
# whatever this misses.

_NL='
'

# Fields interpolated into double-quoted YAML scalars (`name: "%s"`, the model
# key, useModelName) cannot carry a quote, a backslash or a newline. `flags` is
# emitted bare inside a `cmd: >` folded block, so quotes are legal there and
# genuinely needed — --chat-template-kwargs '{"enable_thinking":false}' — but a
# newline would break the block's indentation.
# Entries are read by index, never by id. mval() interpolates its argument into
# the yq expression, so asking it about a model whose *id* holds a quote builds
# a broken query and returns nothing — the one case this most needs to catch.
#
# Every entry is checked, not just the enabled ones: `enabled: no` is exactly
# the bug validate_manifest_booleans() exists for, so "it is parked" cannot be
# assumed while that is still possible.
validate_manifest_strings() {
    local n i id f v rc=0
    n="$(yq -r '.models | length' "$MANIFEST" 2>/dev/null || echo 0)"
    i=0
    while [ "$i" -lt "$n" ]; do
        id="$(yq -r ".models[$i].id // \"(entry $i)\"" "$MANIFEST" 2>/dev/null)"
        for f in id display_name repo; do
            v="$(yq -r ".models[$i].$f // \"\"" "$MANIFEST" 2>/dev/null)"
            case "$v" in
                *'"'*|*\\*|*"$_NL"*)
                    fail "manifest: entry $i ($id) — '$f' has a quote, backslash or newline"
                    note "  value: $(printf '%s' "$v" | tr '\n' ' ')"
                    note "  this is interpolated into quoted YAML and would corrupt the config"
                    rc=1 ;;
            esac
        done
        v="$(yq -r ".models[$i].flags // \"\"" "$MANIFEST" 2>/dev/null)"
        case "$v" in
            *"$_NL"*)
                fail "manifest: entry $i ($id) — 'flags' spans multiple lines"
                note "  keep flags on one line; a block scalar breaks the generated 'cmd: >' block"
                rc=1 ;;
        esac
        i=$((i + 1))
    done
    return $rc
}

# yq follows YAML 1.2, where `no`, `off` and `n` are strings rather than
# booleans. `select(.enabled != false)` therefore keeps a model marked
# `enabled: no` — idiomatic YAML that silently deploys a parked model.
validate_manifest_booleans() {
    local f id v rc=0
    for f in enabled preload; do
        while IFS="$(printf '\t')" read -r id v; do
            [ -n "$id" ] || continue
            case "$v" in
                true|false|null) ;;
                *)  fail "manifest: $id — '$f: $v' is not a boolean"
                    note "  YAML 1.2 reads yes/no/on/off as strings, so '$v' would be ignored"
                    note "  write true or false"
                    rc=1 ;;
            esac
        done <<EOF
$(yq -r ".models[] | [.id, (.$f | tostring)] | @tsv" "$MANIFEST" 2>/dev/null)
EOF
    done
    return $rc
}

_manifest_ok=1
validate_manifest_strings  || _manifest_ok=0
validate_manifest_booleans || _manifest_ok=0
if [ "$_manifest_ok" -eq 0 ]; then
    note "nothing was generated — fix models.yaml and re-run"
    return 0
fi

SWAP_CONFIG="$HOME/.config/llama-swap/config.yaml"
PI_MODELS="$HOME/.pi/agent/models.json"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/local-ai-setup.XXXXXX")"
# shellcheck disable=SC2317
cleanup_tmp() { rm -rf "$TMP_DIR"; }
trap cleanup_tmp EXIT

# A dotfiles-style symlink whose target has been removed makes `mkdir -p` fail
# with a bare ENOENT, which is a baffling thing to read halfway through a run.
# Name the problem instead, and leave the decision to the user — silently
# deleting someone's symlink is not an installer's call to make.
writable_parent() {
    local dir="$1"
    if [ -L "$dir" ] && [ ! -d "$dir" ]; then
        fail "$dir is a symlink to $(readlink "$dir"), which does not exist"
        note "either recreate that target, or replace the symlink with a real directory:"
        note "  rm '$dir' && mkdir -p '$dir'"
        return 1
    fi
    return 0
}

# install_generated <tmp> <dst> <label> <yaml|json>
#
# The parse gate is the point of the fourth argument. Rendering is printf into
# a template, so a manifest value that is perfectly legal YAML on the way in —
# a quote inside display_name, a `flags: |-` literal block — can produce a file
# that is not. Without this check setup prints [install], exits 0, and
# llama-swap's --watch-config picks the broken file straight up on a service
# that was working a second earlier. Parse first, refuse loudly, install never.
install_generated() {
    local tmp="$1" dst="$2" label="$3" kind="$4" keep
    if ! _parses_as "$tmp" "$kind"; then
        keep="$STATE_DIR/invalid-$(basename "$dst")"
        cp "$tmp" "$keep" 2>/dev/null || keep="(could not be saved)"
        fail "$label — generated file is not valid $kind; refusing to install it"
        note "the live config was left alone. The rendered output is at:"
        note "  $keep"
        note "most likely a models.yaml value contains a quote, backslash or newline"
        return 0
    fi
    writable_parent "$(dirname "$dst")" || return 0
    if [ ! -f "$dst" ]; then
        do_install "$label" _place_generated "$tmp" "$dst"
    elif diff -q "$tmp" "$dst" >/dev/null 2>&1; then
        ok "$label"
    else
        do_change "$label" _place_generated "$tmp" "$dst"
    fi
}

_parses_as() {
    case "$2" in
        yaml) yq -e '.' "$1" >/dev/null 2>&1 ;;
        json) jq -e '.' "$1" >/dev/null 2>&1 ;;
        *)    return 0 ;;
    esac
}

_place_generated() {
    local tmp="$1" dst="$2"
    mkdir -p "$(dirname "$dst")"
    backup_file "$dst"
    cp "$tmp" "$dst"
}

# ── A) ~/.config/llama-swap/config.yaml ──────────────────────────────────────
DEF_TTL="$(defval ttl 1800)"
DEF_GMU="$(defval gpu_memory_utilization 0.85)"

# kind_flags <kind> — engine arguments implied by the manifest `kind`.
# Verified against llama-server build 9810: `--rerank, --reranking` and
# `--embedding, --embeddings` both exist; `--pooling` accepts last.
kind_flags() {
    case "$1" in
        embed)  printf -- '--embedding --pooling last' ;;
        rerank) printf -- '--reranking' ;;
        *)      printf '' ;;
    esac
}

render_swap_config() {
    local out="$1" id engine repo ttl gmu kind flags name kflags
    {
        printf '%s\n' "$GEN_HEADER"
        printf 'healthCheckTimeout: 300\n'
        printf 'startPort: 10001\n'
        printf 'globalTTL: %s\n' "$DEF_TTL"
        printf 'captureBuffer: 15                 # request/response capture for the /ui inspector\n'

        # preload hook — warm the coder at boot
        local preloads
        preloads="$(yq -r '.models[] | select(.enabled != false) | select(.preload == true) | .id' "$MANIFEST")"
        if [ -n "$preloads" ]; then
            printf '\nhooks:\n  on_startup:\n    preload:\n'
            while IFS= read -r id; do
                [ -n "$id" ] || continue
                printf '      - "%s"\n' "$id"
            done <<EOF
$preloads
EOF
        fi

        printf '\nmodels:\n'
        for id in $(manifest_ids); do
            engine="$(mval "$id" '.engine' 'rapid-mlx')"
            repo="$(mval "$id" '.repo' '')"
            ttl="$(mval "$id" '.ttl' "$DEF_TTL")"
            gmu="$(mval "$id" '.gpu_memory_utilization' "$DEF_GMU")"
            kind="$(mval "$id" '.kind' 'chat')"
            flags="$(mval "$id" '.flags' '')"
            name="$(mval "$id" '.display_name' '')"

            printf '  "%s":\n' "$id"
            [ -n "$name" ] && printf '    name: "%s"\n' "$name"

            if [ "$engine" = "rapid-mlx" ]; then
                printf '    cmd: >\n'
                printf '      rapid-mlx serve %s\n' "$repo"
                printf '      --gpu-memory-utilization %s\n' "$gmu"
                [ -n "$flags" ] && printf '      %s\n' "$flags"
                # ${PORT} is llama-swap's placeholder — it must survive verbatim.
                # shellcheck disable=SC2016
                printf '      --port ${PORT}\n'
                # rapid-mlx validates the model name in the request body against
                # what it was told to serve, and 404s on the friendly id.
                printf '    useModelName: "%s"\n' "$repo"
            else
                kflags="$(kind_flags "$kind")"
                printf '    cmd: >\n'
                # shellcheck disable=SC2016
                printf '      llama-server --port ${PORT}\n'
                printf '      -hf %s\n' "$repo"
                [ -n "$kflags" ] && printf '      %s\n' "$kflags"
                [ -n "$flags" ] && printf '      %s\n' "$flags"
            fi
            printf '    ttl: %s\n' "$ttl"
        done

        # ── groups ───────────────────────────────────────────────────────────
        # Emitted under routing.router.settings.groups, which is the canonical
        # location in the current schema. The top-level `groups:` key still works
        # but is documented as legacy, and mixing both styles is rejected.
        local pinned utilities heavy
        pinned="$(group_members pinned)"
        utilities="$(group_members utilities)"
        heavy="$(group_members heavy)"

        if [ -n "$pinned$utilities$heavy" ]; then
            printf '\nrouting:\n  router:\n    use: group\n    settings:\n      groups:\n'
            if [ -n "$pinned" ]; then
                printf '        pinned:            # the coder: resident, preloaded, untouchable\n'
                printf '          persistent: true # nothing may evict it (protects the prompt cache)\n'
                printf '          swap: false\n          exclusive: false\n'
                printf '          members: [%s]\n' "$pinned"
            fi
            if [ -n "$utilities" ]; then
                printf '        utilities:         # tiny always-on specialists\n'
                printf '          persistent: true # heavy loads can never evict these\n'
                printf '          swap: false      # they all run together\n          exclusive: false\n'
                printf '          members: [%s]\n' "$utilities"
            fi
            if [ -n "$heavy" ]; then
                printf '        heavy:\n'
                printf '          swap: true       # heavy members swap among themselves\n'
                printf '          exclusive: false # loading one leaves pinned/utilities alone\n'
                printf '          members: [%s]\n' "$heavy"
            fi
        fi
    } >"$out"
}

# group_members <group> — comma-separated quoted ids, "" when the group is empty.
group_members() {
    yq -r ".models[] | select(.enabled != false) | select((.group // \"heavy\") == \"$1\") | .id" \
       "$MANIFEST" 2>/dev/null |
    while IFS= read -r m; do
        [ -n "$m" ] || continue
        printf '"%s", ' "$m"
    done | sed 's/, $//'
}

render_swap_config "$TMP_DIR/config.yaml"
install_generated "$TMP_DIR/config.yaml" "$SWAP_CONFIG" "llama-swap config.yaml" yaml

# ── B) ~/.pi/agent/models.json ───────────────────────────────────────────────
# Only kind: chat models reach Pi. Specialists stay invisible to the picker and
# are reached exclusively through tools.
render_pi_models() {
    local out="$1" chat_models base

    chat_models="$(yq -o=json -I=0 \
        '[.models[]
          | select(.enabled != false)
          | select((.kind // "chat") == "chat")
          | ({"id": .id, "name": (.display_name // .id)} * (.pi // {}))]' "$MANIFEST")"

    # Preserve every other provider; replace only `local`.
    if [ -f "$PI_MODELS" ] && jq -e . "$PI_MODELS" >/dev/null 2>&1; then
        base="$PI_MODELS"
    else
        base="$TMP_DIR/empty.json"
        printf '{"providers":{}}\n' >"$base"
    fi

    jq --argjson models "$chat_models" '
        .providers = (.providers // {})
        | .providers.local = {
            baseUrl: "http://localhost:8080/v1",
            api: "openai-completions",
            apiKey: "local",
            compat: {
              supportsDeveloperRole: false,
              supportsReasoningEffort: false
            },
            models: $models
          }
        | ._generated_by = "local-ai-setup — the local provider is generated from models.yaml"
    ' "$base" >"$out"
}

render_pi_models "$TMP_DIR/models.json"
install_generated "$TMP_DIR/models.json" "$PI_MODELS" "pi models.json" json

# A model Pi still defaults to but that no longer exists leaves the picker
# pointing at nothing. Worth saying out loud rather than silently rewriting
# the user's settings.
PI_SETTINGS="$HOME/.pi/agent/settings.json"
if [ -f "$PI_SETTINGS" ] && jq -e . "$PI_SETTINGS" >/dev/null 2>&1; then
    _default_model="$(jq -r '.defaultModel // empty' "$PI_SETTINGS")"
    if [ -n "$_default_model" ]; then
        if manifest_ids | grep -qx "$_default_model"; then
            ok "pi defaultModel ($_default_model)"
        else
            note "pi settings.json still defaults to '$_default_model', which is not in the manifest"
            note "set it with Pi's /model picker, or edit $PI_SETTINGS"
        fi
    fi
fi
